### ISSUE TITLE
How to launch carddav-to-yealink-remote as a service ?

### ISSUE THREAD

**Issue by Spheerys** [SpiritCroc/carddav-to-yealink-remote#1]
Hi !

First, a big thank you for this very nice script !
It is very helpful :)

For now, I'm launching it with /etc/rc.local file, but I need to restart it sometimes after whitelist ip change.
Moreover, I have to launch it 2 times because I have 2 Yealing phones, so the first script is block the second call.

How do you launch it ?
Did you find a way to launch it as a service ?

**Comment by SpiritCroc** [comment]
Hi, great to hear it's useful for others too! :)
I'm launching it using a systemd service.
If your system uses systemd, this can be basically done by putting following to `/etc/systemd/system/carddav-to-yealink.service`:
```
[Unit]
Description=carddav to yealink contact provider

[Service]
Type=simple
ExecStart=/usr/bin/python3 /installation/path/main.py
User=carddav_bridge
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
```
Then enable with
```
systemctl daemon-reload
systemctl start carddav-to-yealink.service
systemctl enable carddav-to-yealink.service
```

Are you running the script twice for two dav accounts? For two phones, I don't see what speaks against connecting both phones to the same instance of the script, unless they should have different contacts provided.

**Comment by Spheerys** [comment]
Yes it's working well !
I made 2 systemd services because I have 2 different dav accounts :)
